import { type NextPage } from "next";
import Head from "next/head";
import CreateProduct from "~/components/product/create-product";
import CreateUserPost from "~/components/create-user-posts";
import FetchProduct from "~/components/product/fetch-product";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Mini-Ecommerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {/* <CreateUserPost /> */}
        {/* <CreateProduct /> */}
        <FetchProduct />
      </main>
    </>
  );
};

export default Home;
