import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { api } from "~/utils/api";
import { useUser } from "@supabase/auth-helpers-react";
import { useEffect, useState } from "react";
import CreateProduct from "~/components/product/create-product";
import CreateUserPost from "~/components/create-user-posts";
import FetchProduct from "~/components/product/fetch-product";

const Home: NextPage = () => {
  const getProducts = api.product.getProducts.useQuery();

  return (
    <>
      <Head>
        <title>Mini-Ecommerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {/* <CreateUserPost /> */}
        <CreateProduct />
        <FetchProduct />
      </main>
    </>
  );
};

export default Home;
